title: "Minicademy"
email: ruud@minicademy.nl
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: nl_NL
lang: nl_NL
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  ruud:
    name: Ruud
    display_name: Ruud
    avatar: 'assets/images/ruud.png'
    email: ruud@rgonline.nl 
    web: https://www.ruudgreven.nl
    twitter: https://twitter.com/wowthemesnet
    description: "Ruud is de oprichter van Minicademy. Hij is 39, woont alleen in een appartement van 70m2 nabij het centrum van een middelgrote stad. Natuur en parken zijn ook dichtbij. Ruud werkt 3 dagen per week als docent op het HBO en kan daar royaal van rondkomen. Hij heeft geen auto en zijn werk ligt op loopafstand."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
